BUILD_FINGERPRINT=google/tokay_beta/tokay:16/BP31.250502.008/13497110:user/release-keys
BUILD_DESCRIPTION=tokay_beta-user 16 BP31.250502.008 13497110 release-keys
MANUFACTURER_NAME=Google
PRODUCT_BRAND=google
PRODUCT_DEVICE=tokay
PRODUCT_MODEL=Pixel 9
PRODUCT_NAME=tokay_beta
