BUILD_FINGERPRINT=google/oriole_beta/oriole:16/BP22.250221.015/13278879:user/release-keys
BUILD_DESCRIPTION=oriole_beta-user 16 BP22.250221.015 13278879 release-keys
MANUFACTURER_NAME=Google
PRODUCT_BRAND=google
PRODUCT_DEVICE=oriole
PRODUCT_MODEL=Pixel 6
PRODUCT_NAME=oriole_beta
